[package]
name = "musicbrainz-plugin"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
plugin-api = { path = "../plugin_api" }
libloading = "0.8"

ureq = { version = "2.9", features = ["json"] } 
urlencoding = "2.1"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"